@apiurl = http://localhost:3000/api


post {{apiurl}}/users/register
Content-Type: application/json

{
	"username":"teszt",
	"password":"teszt"
}

###

post {{apiurl}}/users/login
content-type: application/json

{
	"username":"teszt",
	"password":"teszt"
}
###

get {{apiurl}}/users/auth

###

post {{apiurl}}/users/logout

###

get {{apiurl}}/listings

###

post {{apiurl}}/listings
Content-Type: application/json

{
	"title":"keresek 1 not",
	"description": "keresek 1 not"
}